version: "3.1"
services:
  fogcomputing_client:
    build: .
    image: ghcr.io/janosbrodbeck/fogcomputing_client:latest
    #container_name: fogcomputing_client
    deploy:
        replicas: 5
    environment:
        CLIENT_REMOTE_HOST: "34.89.169.211"

