version: "3.1"
services:
  fogcomputing_server:
    build: .
    image: ghcr.io/janosbrodbeck/fogcomputing_server:latest
    container_name: fogcomputing_server
    ports:
      - "5000:5000"
    volumes:
      - ./fogcomputing_server:/fogcomputing/
  tcgui:
    image: ncareau/tcgui
    cap_add:
      - NET_ADMIN
    environment:
      TCGUI_PORT: 5555
    network_mode: host
